project:
  type: website
  output-dir: docs

website:
  title: "CDT Conference"
  navbar:
    title: Conference 2025<span class='icon-line'></span>
    right:
      - href: index.qmd#sec-about
        text: About
      - href: index.qmd#sec-keynotes
        text: Keynotes
      - href: index.qmd#sec-agenda
        text: Agenda
      - href: index.qmd#sec-venue
        text: Venue
      - href: index.qmd#sec-organisers
        text: Organisers
      - text: Past Editions
        menu:
          - text: "2024"
            href: https://sites.google.com/view/leedsaimedicalcdtconference?usp=sharing
            target: _blank
  page-footer:  
    left: >-
     Made with [Quarto](https://quarto.org)
    center: |
      <a class="cdt-link" href="https://ai-medical.leeds.ac.uk/" title="CDT Website" target="_blank" rel="noopener">{{< fa globe size=xl >}}</a>
      <a class="cdt-link" href="https://x.com/LeedsMedAI_CDT" title="CDT Twitter" target="_blank" rel="noopener">{{< fa brands twitter size=xl >}}</a>
      <a class="cdt-link" href="https://leeds-ai-cdt.github.io/" title="CDT Blog" target="_blank" rel="noopener">{{< fa blog size=xl >}}</a>
    #right: |
    #  ![](assets/imgs/logos.png){fig-alt="logos" width=300px}
  back-to-top-navigation: true

format:
  html:
    toc: false
    theme: 
      light: [cosmo, assets/styles/light_theme.scss, assets/styles/agenda_style.scss]
      dark: [cosmo, assets/styles/dark_theme.scss, assets/styles/agenda_style.scss]
    css: assets/styles/styles.css
    smooth-scroll: true
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true